services:
  who-1:
    image: bob2606/hello-http:0.8.41
    container_name: who-1
    hostname: who-1
    restart: unless-stopped
    networks:
      whonet:
        ipv4_address: 172.28.0.101
    labels:
      traefik.enable: true
      traefik.http.services.who-1.loadbalancer.server.port: 8080
      traefik.http.routers.who-1.rule: Host(`who-1.stage.local`)

  who-2:
    image: bob2606/hello-http:0.8.41
    container_name: who-2
    hostname: who-2
    restart: unless-stopped
    networks:
      whonet:
        ipv4_address: 172.28.0.102
    labels:
      traefik.enable: true
      traefik.http.services.who-2.loadbalancer.server.port: 8080
      traefik.http.routers.who-2.rule: PathPrefix(`/who-2`)

  who-3:
    image: bob2606/hello-http:0.8.41
    container_name: who-3
    hostname: who-3
    restart: unless-stopped
    networks:
      whonet:
        ipv4_address: 172.28.0.103
    labels:
      traefik.enable: true
      traefik.http.services.who-3.loadbalancer.server.port: 8080

networks:
  whonet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
