---
name: mariadb

services:
  db:
    image: mariadb:11.0
    container_name: mariadb
    volumes:
      - datadb:/var/lib/mysql
    networks:
      phpdbnet:
        ipv4_address: 172.26.0.120
    environment:
      - MARIADB_ROOT_PASSWORD=azerty
      - MARIADB_DATABASE=stage

volumes:
  datadb:

networks:
  phpdbnet:
    name: lemp_phpdbnet
    external: true
